[package]
name = "http_client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10"
tokio = {version="0.2", features= ["full"]}

serde_json = "1.0"


