[package]
name = "redis_sample"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.21.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
