[package]
name = "indicatif"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

indicatif = "0.16.2"
console = { version = ">=0.9.1, <1.0.0", default-features = false }
rand = "0.8"

